version: 2

jobs:

  importPrometheusRules:
    docker:
      - image: web3f/ci-commons:v2.4.0
    steps:
      - checkout
      - run:
          name: Import external alertrules
          command: |
            scripts/alertrules/import.sh

  testPrometheusRules:
    docker:
      - image: web3f/ci-commons:v2.4.0
    steps:
      - checkout
      - run:
          name: Import external alertrules
          command: |
            scripts/alertrules/import.sh
      - run:
          command: |
            scripts/test_prometheus_rules.sh


workflows:
  version: 2
  test-deploy:
    jobs:    
      - importPrometheusRules:
          filters:
            tags:
              only: /.*/
      - testPrometheusRules:
          requires:
            - importPrometheusRules
          filters:
            tags:
              only: /.*/
      - publishChart:
          requires:
            - testPrometheusRules
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
